// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Juliapos.Portal.ProductsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum HttpStatusCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Continue")]
        #pragma warning disable CS1591
        Continue,
        #pragma warning restore CS1591
        [EnumMember(Value = "SwitchingProtocols")]
        #pragma warning disable CS1591
        SwitchingProtocols,
        #pragma warning restore CS1591
        [EnumMember(Value = "Processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "EarlyHints")]
        #pragma warning disable CS1591
        EarlyHints,
        #pragma warning restore CS1591
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "Created")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "Accepted")]
        #pragma warning disable CS1591
        Accepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "NonAuthoritativeInformation")]
        #pragma warning disable CS1591
        NonAuthoritativeInformation,
        #pragma warning restore CS1591
        [EnumMember(Value = "NoContent")]
        #pragma warning disable CS1591
        NoContent,
        #pragma warning restore CS1591
        [EnumMember(Value = "ResetContent")]
        #pragma warning disable CS1591
        ResetContent,
        #pragma warning restore CS1591
        [EnumMember(Value = "PartialContent")]
        #pragma warning disable CS1591
        PartialContent,
        #pragma warning restore CS1591
        [EnumMember(Value = "MultiStatus")]
        #pragma warning disable CS1591
        MultiStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "AlreadyReported")]
        #pragma warning disable CS1591
        AlreadyReported,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMUsed")]
        #pragma warning disable CS1591
        IMUsed,
        #pragma warning restore CS1591
        [EnumMember(Value = "MultipleChoices")]
        #pragma warning disable CS1591
        MultipleChoices,
        #pragma warning restore CS1591
        [EnumMember(Value = "MovedPermanently")]
        #pragma warning disable CS1591
        MovedPermanently,
        #pragma warning restore CS1591
        [EnumMember(Value = "Found")]
        #pragma warning disable CS1591
        Found,
        #pragma warning restore CS1591
        [EnumMember(Value = "SeeOther")]
        #pragma warning disable CS1591
        SeeOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "NotModified")]
        #pragma warning disable CS1591
        NotModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "UseProxy")]
        #pragma warning disable CS1591
        UseProxy,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unused")]
        #pragma warning disable CS1591
        Unused,
        #pragma warning restore CS1591
        [EnumMember(Value = "TemporaryRedirect")]
        #pragma warning disable CS1591
        TemporaryRedirect,
        #pragma warning restore CS1591
        [EnumMember(Value = "PermanentRedirect")]
        #pragma warning disable CS1591
        PermanentRedirect,
        #pragma warning restore CS1591
        [EnumMember(Value = "BadRequest")]
        #pragma warning disable CS1591
        BadRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unauthorized")]
        #pragma warning disable CS1591
        Unauthorized,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaymentRequired")]
        #pragma warning disable CS1591
        PaymentRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "Forbidden")]
        #pragma warning disable CS1591
        Forbidden,
        #pragma warning restore CS1591
        [EnumMember(Value = "NotFound")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "MethodNotAllowed")]
        #pragma warning disable CS1591
        MethodNotAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "NotAcceptable")]
        #pragma warning disable CS1591
        NotAcceptable,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProxyAuthenticationRequired")]
        #pragma warning disable CS1591
        ProxyAuthenticationRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "RequestTimeout")]
        #pragma warning disable CS1591
        RequestTimeout,
        #pragma warning restore CS1591
        [EnumMember(Value = "Conflict")]
        #pragma warning disable CS1591
        Conflict,
        #pragma warning restore CS1591
        [EnumMember(Value = "Gone")]
        #pragma warning disable CS1591
        Gone,
        #pragma warning restore CS1591
        [EnumMember(Value = "LengthRequired")]
        #pragma warning disable CS1591
        LengthRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "PreconditionFailed")]
        #pragma warning disable CS1591
        PreconditionFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "RequestEntityTooLarge")]
        #pragma warning disable CS1591
        RequestEntityTooLarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "RequestUriTooLong")]
        #pragma warning disable CS1591
        RequestUriTooLong,
        #pragma warning restore CS1591
        [EnumMember(Value = "UnsupportedMediaType")]
        #pragma warning disable CS1591
        UnsupportedMediaType,
        #pragma warning restore CS1591
        [EnumMember(Value = "RequestedRangeNotSatisfiable")]
        #pragma warning disable CS1591
        RequestedRangeNotSatisfiable,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExpectationFailed")]
        #pragma warning disable CS1591
        ExpectationFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "MisdirectedRequest")]
        #pragma warning disable CS1591
        MisdirectedRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "UnprocessableEntity")]
        #pragma warning disable CS1591
        UnprocessableEntity,
        #pragma warning restore CS1591
        [EnumMember(Value = "Locked")]
        #pragma warning disable CS1591
        Locked,
        #pragma warning restore CS1591
        [EnumMember(Value = "FailedDependency")]
        #pragma warning disable CS1591
        FailedDependency,
        #pragma warning restore CS1591
        [EnumMember(Value = "UpgradeRequired")]
        #pragma warning disable CS1591
        UpgradeRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "PreconditionRequired")]
        #pragma warning disable CS1591
        PreconditionRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "TooManyRequests")]
        #pragma warning disable CS1591
        TooManyRequests,
        #pragma warning restore CS1591
        [EnumMember(Value = "RequestHeaderFieldsTooLarge")]
        #pragma warning disable CS1591
        RequestHeaderFieldsTooLarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "UnavailableForLegalReasons")]
        #pragma warning disable CS1591
        UnavailableForLegalReasons,
        #pragma warning restore CS1591
        [EnumMember(Value = "InternalServerError")]
        #pragma warning disable CS1591
        InternalServerError,
        #pragma warning restore CS1591
        [EnumMember(Value = "NotImplemented")]
        #pragma warning disable CS1591
        NotImplemented,
        #pragma warning restore CS1591
        [EnumMember(Value = "BadGateway")]
        #pragma warning disable CS1591
        BadGateway,
        #pragma warning restore CS1591
        [EnumMember(Value = "ServiceUnavailable")]
        #pragma warning disable CS1591
        ServiceUnavailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "GatewayTimeout")]
        #pragma warning disable CS1591
        GatewayTimeout,
        #pragma warning restore CS1591
        [EnumMember(Value = "HttpVersionNotSupported")]
        #pragma warning disable CS1591
        HttpVersionNotSupported,
        #pragma warning restore CS1591
        [EnumMember(Value = "VariantAlsoNegotiates")]
        #pragma warning disable CS1591
        VariantAlsoNegotiates,
        #pragma warning restore CS1591
        [EnumMember(Value = "InsufficientStorage")]
        #pragma warning disable CS1591
        InsufficientStorage,
        #pragma warning restore CS1591
        [EnumMember(Value = "LoopDetected")]
        #pragma warning disable CS1591
        LoopDetected,
        #pragma warning restore CS1591
        [EnumMember(Value = "NotExtended")]
        #pragma warning disable CS1591
        NotExtended,
        #pragma warning restore CS1591
        [EnumMember(Value = "NetworkAuthenticationRequired")]
        #pragma warning disable CS1591
        NetworkAuthenticationRequired,
        #pragma warning restore CS1591
    }
}
