// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Juliapos.Portal.ProductsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MeasureMethod
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Count")]
        #pragma warning disable CS1591
        Count,
        #pragma warning restore CS1591
        [EnumMember(Value = "Weigh")]
        #pragma warning disable CS1591
        Weigh,
        #pragma warning restore CS1591
    }
}
