// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Juliapos.Portal.ProductsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductSelectionPageReferenceDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The backColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackColor { get; set; }
#nullable restore
#else
        public string BackColor { get; set; }
#endif
        /// <summary>The columnIdx property</summary>
        public int? ColumnIdx { get; set; }
        /// <summary>The foreColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForeColor { get; set; }
#nullable restore
#else
        public string ForeColor { get; set; }
#endif
        /// <summary>The rowIdx property</summary>
        public int? RowIdx { get; set; }
        /// <summary>The selectionPageId property</summary>
        public Guid? SelectionPageId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Models.ProductSelectionPageReferenceDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Juliapos.Portal.ProductsApi.Models.ProductSelectionPageReferenceDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Juliapos.Portal.ProductsApi.Models.ProductSelectionPageReferenceDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backColor", n => { BackColor = n.GetStringValue(); } },
                { "columnIdx", n => { ColumnIdx = n.GetIntValue(); } },
                { "foreColor", n => { ForeColor = n.GetStringValue(); } },
                { "rowIdx", n => { RowIdx = n.GetIntValue(); } },
                { "selectionPageId", n => { SelectionPageId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("backColor", BackColor);
            writer.WriteIntValue("columnIdx", ColumnIdx);
            writer.WriteStringValue("foreColor", ForeColor);
            writer.WriteIntValue("rowIdx", RowIdx);
            writer.WriteGuidValue("selectionPageId", SelectionPageId);
        }
    }
}
#pragma warning restore CS0618
