// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Juliapos.Portal.ProductsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductVariationLocationDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The changeDateTime property</summary>
        public DateTimeOffset? ChangeDateTime { get; set; }
        /// <summary>The locationId property</summary>
        public Guid? LocationId { get; set; }
        /// <summary>The maxAmount property</summary>
        public float? MaxAmount { get; set; }
        /// <summary>The minAmount property</summary>
        public float? MinAmount { get; set; }
        /// <summary>The nextStatus property</summary>
        public global::Juliapos.Portal.ProductsApi.Models.ProductStatus? NextStatus { get; set; }
        /// <summary>The onMenuEnd property</summary>
        public Time? OnMenuEnd { get; set; }
        /// <summary>The onMenuStart property</summary>
        public Time? OnMenuStart { get; set; }
        /// <summary>The showOnFavoritePage property</summary>
        public bool? ShowOnFavoritePage { get; set; }
        /// <summary>The status property</summary>
        public global::Juliapos.Portal.ProductsApi.Models.ProductStatus? Status { get; set; }
        /// <summary>The transport property</summary>
        public float? Transport { get; set; }
        /// <summary>The unitPrice property</summary>
        public float? UnitPrice { get; set; }
        /// <summary>The unitPricePurchase property</summary>
        public float? UnitPricePurchase { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Models.ProductVariationLocationDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Juliapos.Portal.ProductsApi.Models.ProductVariationLocationDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Juliapos.Portal.ProductsApi.Models.ProductVariationLocationDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "changeDateTime", n => { ChangeDateTime = n.GetDateTimeOffsetValue(); } },
                { "locationId", n => { LocationId = n.GetGuidValue(); } },
                { "maxAmount", n => { MaxAmount = n.GetFloatValue(); } },
                { "minAmount", n => { MinAmount = n.GetFloatValue(); } },
                { "nextStatus", n => { NextStatus = n.GetEnumValue<global::Juliapos.Portal.ProductsApi.Models.ProductStatus>(); } },
                { "onMenuEnd", n => { OnMenuEnd = n.GetTimeValue(); } },
                { "onMenuStart", n => { OnMenuStart = n.GetTimeValue(); } },
                { "showOnFavoritePage", n => { ShowOnFavoritePage = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Juliapos.Portal.ProductsApi.Models.ProductStatus>(); } },
                { "transport", n => { Transport = n.GetFloatValue(); } },
                { "unitPrice", n => { UnitPrice = n.GetFloatValue(); } },
                { "unitPricePurchase", n => { UnitPricePurchase = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("changeDateTime", ChangeDateTime);
            writer.WriteGuidValue("locationId", LocationId);
            writer.WriteFloatValue("maxAmount", MaxAmount);
            writer.WriteFloatValue("minAmount", MinAmount);
            writer.WriteEnumValue<global::Juliapos.Portal.ProductsApi.Models.ProductStatus>("nextStatus", NextStatus);
            writer.WriteTimeValue("onMenuEnd", OnMenuEnd);
            writer.WriteTimeValue("onMenuStart", OnMenuStart);
            writer.WriteBoolValue("showOnFavoritePage", ShowOnFavoritePage);
            writer.WriteEnumValue<global::Juliapos.Portal.ProductsApi.Models.ProductStatus>("status", Status);
            writer.WriteFloatValue("transport", Transport);
            writer.WriteFloatValue("unitPrice", UnitPrice);
            writer.WriteFloatValue("unitPricePurchase", UnitPricePurchase);
        }
    }
}
#pragma warning restore CS0618
