// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Juliapos.Portal.ProductsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProductStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Activated")]
        #pragma warning disable CS1591
        Activated,
        #pragma warning restore CS1591
        [EnumMember(Value = "Deactivating")]
        #pragma warning disable CS1591
        Deactivating,
        #pragma warning restore CS1591
        [EnumMember(Value = "Deactivated")]
        #pragma warning disable CS1591
        Deactivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "Deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
    }
}
