// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Juliapos.Portal.ProductsApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VatLevel
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Low")]
        #pragma warning disable CS1591
        Low,
        #pragma warning restore CS1591
        [EnumMember(Value = "High")]
        #pragma warning disable CS1591
        High,
        #pragma warning restore CS1591
    }
}
