// <auto-generated/>
#pragma warning disable CS0618
using Juliapos.Portal.ProductsApi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Juliapos.Portal.ProductsApi.Api.V1.Dustcategories.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\dustcategories\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DustcategoriesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.Dustcategories.Item.DustcategoriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DustcategoriesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dustcategories/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.Dustcategories.Item.DustcategoriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DustcategoriesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dustcategories/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a menu category
        /// </summary>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "409", global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto>(requestInfo, global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get dust category with id as parameter
        /// </summary>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto">When receiving a 400 status code</exception>
        /// <exception cref="global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto.CreateFromDiscriminatorValue },
                { "404", global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto>(requestInfo, global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a dust category
        /// </summary>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto"/></returns>
        /// <param name="body">DTO for updating a dust category</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto">When receiving a 404 status code</exception>
        /// <exception cref="global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto?> PutAsync(global::Juliapos.Portal.ProductsApi.Models.DustCategoryUpdateDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto> PutAsync(global::Juliapos.Portal.ProductsApi.Models.DustCategoryUpdateDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto.CreateFromDiscriminatorValue },
                { "409", global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto>(requestInfo, global::Juliapos.Portal.ProductsApi.Models.DustCategoryDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a menu category
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get dust category with id as parameter
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a dust category
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">DTO for updating a dust category</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Juliapos.Portal.ProductsApi.Models.DustCategoryUpdateDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Juliapos.Portal.ProductsApi.Models.DustCategoryUpdateDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.Dustcategories.Item.DustcategoriesItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Dustcategories.Item.DustcategoriesItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Juliapos.Portal.ProductsApi.Api.V1.Dustcategories.Item.DustcategoriesItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DustcategoriesItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DustcategoriesItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DustcategoriesItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
