// <auto-generated/>
#pragma warning disable CS0618
using Juliapos.Portal.ProductsApi.Api.V1.Customattributes;
using Juliapos.Portal.ProductsApi.Api.V1.Dustcategories;
using Juliapos.Portal.ProductsApi.Api.V1.Menucategories;
using Juliapos.Portal.ProductsApi.Api.V1.Productcategories;
using Juliapos.Portal.ProductsApi.Api.V1.Products;
using Juliapos.Portal.ProductsApi.Api.V1.Selectionpages;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Juliapos.Portal.ProductsApi.Api.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The customattributes property</summary>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.CustomattributesRequestBuilder Customattributes
        {
            get => new global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.CustomattributesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dustcategories property</summary>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Dustcategories.DustcategoriesRequestBuilder Dustcategories
        {
            get => new global::Juliapos.Portal.ProductsApi.Api.V1.Dustcategories.DustcategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The menucategories property</summary>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Menucategories.MenucategoriesRequestBuilder Menucategories
        {
            get => new global::Juliapos.Portal.ProductsApi.Api.V1.Menucategories.MenucategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The productcategories property</summary>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Productcategories.ProductcategoriesRequestBuilder Productcategories
        {
            get => new global::Juliapos.Portal.ProductsApi.Api.V1.Productcategories.ProductcategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Products.ProductsRequestBuilder Products
        {
            get => new global::Juliapos.Portal.ProductsApi.Api.V1.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The selectionpages property</summary>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Selectionpages.SelectionpagesRequestBuilder Selectionpages
        {
            get => new global::Juliapos.Portal.ProductsApi.Api.V1.Selectionpages.SelectionpagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
