// <auto-generated/>
#pragma warning disable CS0618
using Juliapos.Portal.ProductsApi.Api.V1.Customattributes.Item;
using Juliapos.Portal.ProductsApi.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Juliapos.Portal.ProductsApi.Api.V1.Customattributes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\customattributes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomattributesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Juliapos.Portal.ProductsApi.api.v1.customattributes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.Item.CustomattributesItemRequestBuilder"/></returns>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.Item.CustomattributesItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.Item.CustomattributesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Juliapos.Portal.ProductsApi.api.v1.customattributes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.Item.CustomattributesItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.Item.CustomattributesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.Item.CustomattributesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.CustomattributesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomattributesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/customattributes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.CustomattributesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomattributesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/customattributes", rawUrl)
        {
        }
        /// <summary>
        /// Get custom attributes
        /// </summary>
        /// <returns>A List&lt;global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto>(requestInfo, global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Create a new custom attribute
        /// </summary>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto"/></returns>
        /// <param name="body">DTO for adding a custom attribute</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto?> PostAsync(global::Juliapos.Portal.ProductsApi.Models.CustomAttributeAddDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto> PostAsync(global::Juliapos.Portal.ProductsApi.Models.CustomAttributeAddDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "409", global::Juliapos.Portal.ProductsApi.Models.ErrorResultDto.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto>(requestInfo, global::Juliapos.Portal.ProductsApi.Models.CustomAttributeDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get custom attributes
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new custom attribute
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">DTO for adding a custom attribute</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Juliapos.Portal.ProductsApi.Models.CustomAttributeAddDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Juliapos.Portal.ProductsApi.Models.CustomAttributeAddDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.CustomattributesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.CustomattributesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Juliapos.Portal.ProductsApi.Api.V1.Customattributes.CustomattributesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CustomattributesRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CustomattributesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
